[package]
name = "rerun"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
chrono = "0.4"
vm-launcher = { path = "../vm-launcher" }

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true


